{% set name = "urdfpy" %}
{% set version = "0.1.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mmatl/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 283de7410d57198eb5845f899fdffd17edd13b32ecdc1f2d130c3ed6da47cdc0
  patches:
    - relax_pycollada_req.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - lxml
    - networkx ==2.2
    - numpy
    - pillow
    - pip
    - pycollada
    - pyrender >=0.1.20
    - python >=3.6
    - scipy
    - six
    - trimesh
  run:
    - lxml
    - networkx ==2.2
    - numpy
    - pillow
    - pycollada
    - pyrender >=0.1.20
    - python >=3.6
    - scipy
    - six
    - trimesh

test:
  imports:
    - urdfpy
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/mmatl/urdfpy
  summary: URDF parser and manipulator for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
